### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by happyzhanglol** [GGchen1997/STEPS_Bioinformatics#1]
Hello, Dear professor Chen. Could you give your processed pdb datasets, Please!

**Comment by happyzhanglol** [comment]
Because some pdb files have Non-standard residues that don't have CA atoms, so that  transforming those pdb files to The Graph would face some problems. So i want to kown how do you preprocess those pdb files. Please let me know when you see it. Thank you!

**Comment by GGchen1997** [comment]
Thanks for your question. The PDB files provided in Alphafold2 are standard and you could directly operate on them.
