### ISSUE TITLE
One question about  enzyme- catalyzed reaction classification

### ISSUE THREAD

**Issue by happyzhanglol** [GGchen1997/STEPS_Bioinformatics#2]
Hello, I have a question about  enzyme- catalyzed reaction classification.  You say that the downstream task are available in IEConv, However, The IEConv hdf5 file doesn't give the information which you need to build your graph because the hdf5 file lack the seq, angle and so on. How could you do that  enzyme-catalyzed reaction classification?

**Comment by GGchen1997** [comment]
Yes, we some database to build the graph only for part of the files with structure.
