### ISSUE TITLE
Where are the pdb files for C2 (water) and C10 (loc)?

### ISSUE THREAD

**Issue by OrangeCat7777777** [GGchen1997/STEPS_Bioinformatics#4]
It seems that they come from the DeepLoc paper, but they only provide fasta file.

**Comment by GGchen1997** [comment]
Thanks for your question. The issue notifications go to my another email which I do not use. I will update you soon.

**Comment by GGchen1997** [comment]
Yes, the DeepLoc paper indeed provides only the FASTA file for the protein sequences. Each sample within this file has two labels: one indicating the protein's location and the other its membrane association. For our purposes, we'll need to separate these two labels to properly utilize them in our analysis or model training.
