### ISSUE TITLE
Can you provide a complete data set to let the project run 

### ISSUE THREAD

**Issue by IBelieve1234** [GGchen1997/STEPS_Bioinformatics#5]
Can you provide a complete data set to let the project run which contains deeploc/enzyme_stru.npy  deeploc/stru_pdb.npy  deeploc/water/train.npy and so on.

**Comment by GGchen1997** [comment]
Thanks for your question. The issue notifications go to my another email which I do not use. I will update you soon.

**Comment by IBelieve1234** [comment]
大佬，谢谢回复!代码已经跑通，论文思路真棒!



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 23, 2024 23:18 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [GGchen1997/STEPS_Bioinformatics] Can you provide a complete dataset to let the project run  (Issue #5)




 
Thanks for your question. The issue notifications go to my another email which I do not use. I will update you soon.

**Comment by Tiantao2000** [comment]
I also have this queation, could you provide the complete dataset? Thanks.
