### ISSUE TITLE
where is the file of mutualinfo.pt

### ISSUE THREAD

**Issue by IBelieve1234** [GGchen1997/STEPS_Bioinformatics#6]
Dear professor Chen，could u provide the file of mutualinfo.pt，thanks！

**Comment by GGchen1997** [comment]
Thanks for your question. The issue notifications go to my another email which I do not use. I will update you soon.

**Comment by GGchen1997** [comment]
Hi, I regret to inform you that the mutualinfo.pt file has been deleted from the server. However, you can recreate this file by pre-training a model yourself. Simply use the sequential from LM and structural representations as inputs and minimize the Mutual Information loss. This will yield a pre-trained model that can serve as a starting point for your experiments. Afterwards, main.py can further adjust this pre-trained model as needed. Or you could neglect the mutualinfo.pt file and directly train it in the main.py

**Comment by IBelieve1234** [comment]
really thank u! I have Solved all the problems.

**Comment by GGchen1997** [comment]
[like]  Can Chen reacted to your message:
________________________________
