### ISSUE TITLE
using pre-trained model for my downstream task

### ISSUE THREAD

**Issue by niloole** [GGchen1997/STEPS_Bioinformatics#7]
Hello
I want to use the pre-trained model to find representation and do my own downstream task. but according in these lines:

```
train_index1 = list(np.load("deeploc/stru_pdb.npy", allow_pickle=True))
train_index2 = list(np.load("deeploc/enzyme_stru.npy", allow_pickle=True))
```
the **deeploc** folder and **npy** files do not exist. How can I use your pre-trained model for my downstream task?
Thanks in advance

**Comment by GGchen1997** [comment]
Thanks for your question. The issue notifications go to my another email which I do not use. I will update you soon.

**Comment by GGchen1997** [comment]
Hello,

The train_index1 and train_index2 lines in the code reference specific protein files (stru_pdb.npy and enzyme_stru.npy) used for pre-training our model. These files indicate which proteins were included in the training process. For your tasks, you're not limited to our dataset. You can train the model on any subset of the AlphaFold database or a similar protein structure dataset by preparing your .npy files with indices of your chosen proteins. This flexibility allows the pre-trained model to be adapted to various research needs.
